// <auto-generated />
namespace MyRentalPos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12));
        
        string IMigrationMetadata.Id
        {
            get { return "201301151936305_v1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
