// <auto-generated />
namespace MyRentalPos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v11));
        
        string IMigrationMetadata.Id
        {
            get { return "201301142144338_v1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
