// <auto-generated />
namespace MyRentalPos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v10));
        
        string IMigrationMetadata.Id
        {
            get { return "201301142121053_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
